### ISSUE TITLE
TenMinecraftChallenges.CLASS not in correct location

### ISSUE THREAD

**Issue by AbyssStudios** [AbyssStudios/TenMinecraftChallenges#2]
We can't figure out how to move the [TenMinecraftChalleges.CLASS](https://github.com/AbyssStudios/TenMinecraftChallenges/TenMinecraftChallenges.class) to another directory. If you know how to do this, please help! Thanks! :)

**Comment by davidkey** [comment]
Hi there,

Just to make sure I understand the issue - do you want to place the class at a different location during the compile phase? Are you trying to move the class file to somewhere else on the file system or inside the jar itself?

(found this issue by looking through [help wanted] tags :)

**Comment by AbyssStudios** [comment]
Neither, we just wanted to move the file in the GitHub. We fixed it. Thanks! :D
